apiVersion: 1

deleteDatasources:
  - name: Apple Watch InfluxDB
    orgId: 1

datasources:
  - name: Apple Watch InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://apple_watch_influxdb:8086
    jsonData:
      dbName: apple_watch
      httpHeaderName1: 'Authorization'
      timeInterval: 1d
    secureJsonData:
      httpHeaderValue1: 'Token $APPLE_WATCH_INFLUX_TOKEN'
    isDefault: true
    editable: true
    options:
      path: /etc/grafana/provisioning/dashboards
