apiVersion: 1

deleteDatasources:
  - name: Apple Watch InfluxDB
    orgId: 1

datasources:
  - name: Apple Watch InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://apple_watch_influxdb:8086
    jsonData:
      version: Flux
      organization: my_org
      defaultBucket: apple_watch
      tlsSkipVerify: true
    secureJsonData:
      token: my_token
    isDefault: true
    editable: true
    options:
      path: /etc/grafana/provisioning/dashboards
